apiVersion: v2
name: donetick
description: Donetick helm chart for Kubernetes
type: application
version: 1.0.1
appVersion: "v0.1.38"
maintainers:
  - name: Richard Tomik
    email: no@m.com
keywords:
  - productivity
  - task-management
  - donetick
home: https://github.com/rtomik/helm-charts
sources:
  - https://github.com/donetick/donetick