apiVersion: v2
name: paperless-ngx
description: Paperless-ngx helm chart for Kubernetes
type: application
version: 0.0.3
appVersion: "latest"
maintainers:
  - name: Richard Tomik
    email: richard.tomik@proton.me
keywords:
  - productivity
  - document-management
  - paperless
  - paperless-ngx
  - ocr
home: https://github.com/rtomik/helm-charts
sources:
  - https://github.com/paperless-ngx/paperless-ngx