{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-data
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
  {{- with .Values.persistence.data.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode | quote }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
---
{{- end }}

{{- if and .Values.persistence.media.enabled (not .Values.persistence.media.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-media
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
  {{- with .Values.persistence.media.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.media.accessMode | quote }}
  {{- if .Values.persistence.media.storageClass }}
  storageClassName: {{ .Values.persistence.media.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size | quote }}
---
{{- end }}

{{- if and .Values.persistence.export.enabled (not .Values.persistence.export.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-export
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
  {{- with .Values.persistence.export.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.export.accessMode | quote }}
  {{- if .Values.persistence.export.storageClass }}
  storageClassName: {{ .Values.persistence.export.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.export.size | quote }}
---
{{- end }}

{{- if and .Values.persistence.consume.enabled (not .Values.persistence.consume.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-consume
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
  {{- with .Values.persistence.consume.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.consume.accessMode | quote }}
  {{- if .Values.persistence.consume.storageClass }}
  storageClassName: {{ .Values.persistence.consume.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.consume.size | quote }}
{{- end }}